In [4]:
import numpy as np

In [5]:

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

## Task: From a, select elements that are divisible by 2

In [7]:
a[a%2 ==0]

array([ 2,  4,  6,  8, 10, 12])

## Task: From a, select elements that are greater than 2 and less than or equal to 10

In [9]:
a>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
a<=10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [17]:
a[(a>2) & (a<=10)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])