## **Numpy Tutorial**


In [2]:
import numpy as np

In [6]:
## Task: From a, select elements that are ddivisible by 2
nums = np.array([5, 6, 7, 8, 9, 10, 11, 12])
final = []

for num in nums:
    if num % 2 == 0:
        final.append(num)

print(final)

[np.int64(6), np.int64(8), np.int64(10), np.int64(12)]


In [10]:
## Task: From a, select elements that are greater than 2 and less than or equal to 10
check=[]
for num in nums:
    if num > 2 and num < 10:
        check.append(num)
print(check)

[np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]


In [12]:
## Testing Numpy Functionality
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a= a* 2
a

array([[0.90106628, 0.34593554, 0.6875249 , 1.1021304 ],
       [1.0925463 , 0.10187174, 0.80135322, 1.11291986],
       [0.25395256, 1.64970286, 0.53181112, 1.13834202]])

In [14]:
#Finding the minimum from array a
a .min()


np.float64(0.10187174)

In [18]:
#creating a matrix
data = np.array ([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [22]:
data.max (axis=0)
data.max (axis=1)

array([2, 5, 6])

In [24]:

##Matrix Operation on matirx of different size


data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[2,2]])
data + ones_row

array([[3, 4],
       [5, 6],
       [7, 8]])

In [28]:
##Random Number generation
rng = np.random  # the simplest way to generate random numbers
rng.random(3)

array([0.22851071, 0.58251972, 0.07558594])

In [30]:
##Get unique elements from an array 
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)
     

[11 12 13 14 15 16 17 18 19 20]


In [34]:
## Get indice along with unique element


a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, indices_list = np.unique(a, return_index=True)
print(f"Unique Values: {unique_values}")
print(f"Indices List: {indices_list}")
     

Unique Values: [11 12 13 14 15 16 17 18 19 20]
Indices List: [ 0  2  3  4  5  6  7 12 13 14]


In [45]:
##For 2D array getting unique
data = np.array([[1, 2, 5, 6, 7, 7 ], [1, 0, 3, 4, 5, 6], [2, 1, 0, 8, 9, 5]])
np.unique(data)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
##Reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]
